<?php

/**
 * @return \Xtuple\REST\Client\Configuration
 * @throws \Exception
 */
function rescued_get_configuration() {
  global $rescued_config;
  if (empty($rescued_config)) {
    throw new Exception("RESCUED configuration is not set");
  }
  return $rescued_config;
}

/**
 * Shortcut to get application name
 */
function rescued_application_name() {
  return rescued_api_get_client()->applicationName();
}

/**
 * @return \Xtuple\REST\Client\Client
 * @throws \Exception
 */
function rescued_api_get_client() {
  static $client;
  if (!isset($client)) {
    $configuration = rescued_get_configuration();
    /** @var Xtuple\Xdruple\Session\RescuedSession $session */
    global $session;
    $client = new \Xtuple\REST\Client\Client($configuration, $session);
  }
  return $client;
}
